name: Mirror all branches to GitLab via HTTPS

# Se dispara con cualquier push (cualquier rama / tag)
on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror to GitLab via HTTPS
        env:
          GITLAB_PAT: ${{ secrets.GITLAB_PAT }}
        run: |
          # Añadimos el remote apuntando a tu GitLab self-hosted usando el PAT
          git remote add gitlab "https://oauth2:${GITLAB_PAT}@git.planificando.net/jesus.palomino/SyntehticDataSuite.git"
          # Push de todas las refs (ramas, tags, etc.)
          git push --mirror gitlab
