name: Mirror branches & tags to GitLab via HTTPS

on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add GitLab remote
        run: |
          git remote add gitlab "https://oauth2:${{ secrets.GITLAB_PAT }}@git.planificando.net/jesus.palomino/SyntehticDataSuite.git"

      - name: Push all branches to GitLab
        run: |
          # Empuja cada rama local a GitLab (prune elimina las que ya no existen)
          git push gitlab --prune --force refs/heads/*:refs/heads/*

      - name: Push all tags to GitLab
        run: |
          # Empuja todas las etiquetas
          git push gitlab --prune --tags
